### ISSUE TITLE
Bookmarks order is not kept

### ISSUE THREAD

**Issue by Blagatt** [Kapcash/bookmark-switcher#1]
Greetings,

I like my bookmarks to be at a specific place and in a specific order but when switching from one bar to another, the order changes.

Anything you can do about this?

**Comment by Kapcash** [comment]
Thanks for filling in this issue :)

I just released a new version (v1.1.0) of the addons. It should improve this problem.

This kind of problematic is a bit hard to reproduce but I did my best to address it.
Let me know if it works better for you!

**Comment by Kapcash** [comment]
This has been definitely issues in version v1.1.2!
It will now move each bookmark sequentially, guaranteeing the bookmarks order :)

Again, let me know if you encounter other bugs!
