### ISSUE TITLE
Feature Request: Non-Synced Active Bookmark Bar

### ISSUE THREAD

**Issue by petebaker17** [Kapcash/bookmark-switcher#10]
Is there an ability to make it so different computers using the same firefox account don't sync the active bookmark bar, as it always changes to the last used one?

**Comment by Kapcash** [comment]
Not yet, but I can add this feature when I find some time for it!

**Comment by petebaker17** [comment]
Thank you very much! I really like the extension, is very clean and easy to use!

**Comment by Kapcash** [comment]
Hi @petebaker17! 
I just released the version 2.1.0 which adds this exact feature. It's available from the "preferences" tab of the extension within the `about:addons` page on Firefox.

Let me know if it works as you expect it to or if you find any bugs!

**Comment by petebaker17** [comment]
Oh wow! Thanks, I'll test this out and get back if there are any issues :)

**Comment by Kapcash** [comment]
No news, good news!
Feel free to reopen if the issue persists.
