### ISSUE TITLE
Icon selector for Bars is broken

### ISSUE THREAD

**Issue by hojerst** [Kapcash/bookmark-switcher#16]
Trying to change an Icon of a bar will result in an empty list (with an empty item called "None") in the icon list. This worked in the past, but seems broken now.

<img width="245" alt="Screenshot 2024-03-21 at 10 49 18" src="https://github.com/Kapcash/bookmark-switcher/assets/436889/cfca91ab-f923-43c7-9868-825c8b04ea2a">

Affected Browser: Firefox 124.0 on MacOS 14.4 - other OSes seem to be affected as well, though.

**Comment by Kapcash** [comment]
Hi @hojerst! Indeed, thank you for reporting this :)

I'm using this api to fetch the list of emojis: https://emoji-api.com/#documentation
It's still under development according to their website, and they recently changed the unicode name of the emojis. So my code was filtering out all of them now.

I fixed this in the latest version v2.1.1 that should be published soon!
