### ISSUE TITLE
feature request: allow to have a common set of bookmarks

### ISSUE THREAD

**Issue by hojerst** [Kapcash/bookmark-switcher#2]
Hi!

First of all: Thanks for this great extentsion. I use this to switch between a bookmark bar for work and hobby.

Would it be possible to implement a feature to leave some bookmarks shared between bars? I really like to have a very small set of bookmarks in all of my bars (e.g. links to internal systems of my homelab).

Implementation Idea: completely ignore all bookmarks with a specific tag and moving everything else around as normal.

**Comment by Kapcash** [comment]
Hi @hojerst! As you have seen it, I have implemented this feature on the last version of the extension ([v2.0.0](https://github.com/Kapcash/bookmark-switcher/releases/tag/v2.0.0)).

Feel free to reopen this issue if you have any feedbacks / problems with the feature :)
