### ISSUE TITLE
Version 2.0.0 fails to properly show popup on Waterfox G4.1.3.2

### ISSUE THREAD

**Issue by sir-e-Bob** [Kapcash/bookmark-switcher#4]
Hi!

Thank you very much for creating this useful extension!

Sadly, the newest version 2.0.0 doesn't seem to work well with the current version of the Waterfox browser (G4.1.3.2 (64-bit)), while the previous version (1.2.0) does work with it.

The problem is that when I click the extension icon, instead of the expected popup showing, all I get is a thin line (presumably the top border of the popup):

![image](https://user-images.githubusercontent.com/109518735/179553011-eef25b05-bc91-4e7c-b3a9-0e67dc17a096.png)

While I understand that you cannot guarantee that your extension works with every browser out there, I am a bit puzzled that it used to work fine in the past while the latest version doesn't.

Now I have to say that I also tried adding it to an old version of Firefox (94.0.2) and the exact same issue occurred. However, after Firefox updated itself to the latest version (102.0.1), it now works fine there.
(There are a couple of minor issues there as well, for which I will file separate reports.)

So it could be that Waterfox simply hasn't caught up yet to the newest Firefox developments and that your extension will work again with a forthcoming Waterfox release.
In the meantime I reverted to the previous version 1.2.0 of Bookmark Switcher, making sure to disable auto-updates.

If there is nothing else to do but to wait for a new Waterfox version that meets the requirements of Bookmark Switcher version 2.0.0, then feel free to close this issue.
But I felt that I should at least let you know about this incompatibility.

Thank you again for your work on this great extension!

**Comment by Kapcash** [comment]
Hi! Thank you very much for taking the time to fill this issue!

I fixed it already and published the fixed 2.0.1 version. Let me know if it works better now.

For the technical record: I was unintentionnaly using a non-specified api as `storage.sync.onChanged` instead of the official  documentated `storage.onChanged` method. Latests Firefox versions seems to set this function under both `storage` and `storage[storeType]` objects, which lead me to use an undocumented function.

**Comment by sir-e-Bob** [comment]
Excellent! It works correctly now.

Thank you for the fast update and the detailed explanation!

Merci beaucoup!
