### ISSUE TITLE
Pressing Enter does not commit bookmark bar name changes

### ISSUE THREAD

**Issue by sir-e-Bob** [Kapcash/bookmark-switcher#5]
Hi,

Thank you so much for the new version 2.0.0 of Bookmark Switcher!

One little thing that caught me by surprise however, is that pressing the [Enter] key on the keyboard doesn't seem to commit changes made when editing the name of a bookmark bar. (This did work with the previous version 1.2.0.) Instead, it seems necessary to click the "Go back" arrow below the name field. This seems a bit counter-intuitive to me, since I would actually have expected this action to _cancel_ the edits.

This behavior was observed with version 102.0.1 of Firefox.

**Comment by Kapcash** [comment]
This should be fixed with the new 2.0.2 version!
Now, by pressing "enter" on the edit page, it will keep the current change you made on the input, and get you back to the previous page.

Let me know how you feel about this change and if you would like it to behave differently :)

**Comment by sir-e-Bob** [comment]
Great! Pressing "Enter" works as I would expect now.

Thank you very much!
