### ISSUE TITLE
Original extension icon not restored when current bookmark bar no longer has icon

### ISSUE THREAD

**Issue by sir-e-Bob** [Kapcash/bookmark-switcher#6]
Hi,

When adding an icon for the current bookmark bar, the extension icon updates to show that icon as well, which is a nice feature. Thank you!

![image](https://user-images.githubusercontent.com/109518735/179559759-f9aff92d-3151-4e41-8f57-cc867b931fe3.png)

But when switching to a bar without icon afterwards, the extension icon looks like this:

![image](https://user-images.githubusercontent.com/109518735/179559853-1df3fe4a-c21c-4303-be1f-b98b0c5a5a02.png)

The same happens when removing the icon for the current bookmark bar:

![image](https://user-images.githubusercontent.com/109518735/179559932-78cfffe4-2757-4121-a8d4-d30bc059f4a2.png)

Wouldn't it look better if the original extension icon were restored in these cases? This mostly empty icon looks a bit strange to me.

This behavior was observed with version 102.0.1 of Firefox.

**Comment by Kapcash** [comment]
This should be fixed with the new 2.0.2 version.
Let me know if it works fine for you, it's a bit hard to check for every screen size/resolution how it renders!
(Feel free to reopen this conversation if you feel it still needs some changes)

**Comment by sir-e-Bob** [comment]
For me the icon renders fine now, thanks!

Your dedication to this wonderful extension is much appreciated!
