### ISSUE TITLE
Options don't display.

### ISSUE THREAD

**Issue by JohnLukeBentley** [Kapcash/bookmark-switcher#7]
Reproduce:

* Firefox > Hamburger Menu > Settings ... > Extensions > Bookmark switcher > |Options|
* "File Not Found" displays momentarily before being pushed (infinitely?) toward the bottom of the page.

Expect:
* At least informational text on this page (e.g. "There are no options"); or, better, an option to change the switching keyboard shortcut.

But generally a fantastic extension. Very handy. Thanks for releasing it.

**Comment by Kapcash** [comment]
Thank you so much for reporting this error.
An option to update the shortcut would be very nice indeed, since the option given by Firefox is hard to find.
I'll make it possible in the next release!

**Comment by JohnLukeBentley** [comment]
On the (separate but related) issue of the keyboard shortcut ...

Your current default choice, alt+space, conflicts with Microsoft PowerToys Search. Some possible things you could do:

* Choose another default choice; and/or
* In your options keep this default choice but offer the user a few handy alternatives, in addition to a custom option. E.g.

```
Switching Keyboard Shortcut:

[x] Alt + Space;
[x] Alt + Space + Enter;
[x] Alt + 12
[x] Custom: [           ]
```

The above example alternatives just come randomly to mind. As to suggested alternatives that are well chosen ... that'd require some further thought. :)

**Comment by Kapcash** [comment]
I just released a new version that removes this empty options panel on the browser :)

Meanwhile, I'm working on adding a legit option to update the shortcut, so it's easier for users to change it. Changing it through the browser is tedious and kind of hidden...

It will also replace the default one on Windows because I understand it's conflicting with the OS.
